name: Terraform Tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main

  push:
    branches:
    - main

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform-tests:
    uses: ./.github/workflows/reusable-terraform-test.yaml
    with:
      modules_root: modules
      terraform_version: 1.13.4
      comment_on_pr: true
      pull_request_number: ${{ github.event.pull_request.number || '' }}